### ISSUE TITLE
Contact form doesn't work

### ISSUE THREAD

**Issue by LilianBoulard** [boulard-family/boulard.fr#1]

**Comment by rocklikereeju00** [comment]
Can I work in this project

**Comment by Phaide** [comment]
Hi @rocklikereeju00 

Sure, if you wish to contribute you're more than welcome !
If you want to submit code, please do and I'll review it.
If you want to discuss, please contact me on Telegram `@Phaide_phd`.
Thanks

**Comment by LilianBoulard** [comment]
Solved in f2bd4dd5f6e0a9133b90af368fd200f447f25418
